import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_USER || "nickdavis0124@gmail.com",
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

export async function sendPodcastEmail(
  to: string,
  topic: string,
  duration: string,
  audioBuffer: Buffer,
  failedUrls?: string[]
): Promise<void> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");

  let htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1a1a1a;">Your podcast is ready!</h2>
      <p><strong>Topic:</strong> ${escapeHtml(topic)}</p>
      <p><strong>Duration:</strong> ${duration} minutes</p>
      <p>Please find your podcast attached to this email.</p>
  `;

  if (failedUrls && failedUrls.length > 0) {
    htmlBody += `
      <p style="color: #b45309; margin-top: 16px;">
        <strong>Note:</strong> The following URLs could not be fetched and were not included in the podcast content:
      </p>
      <ul style="color: #b45309;">
        ${failedUrls.map((url) => `<li>${escapeHtml(url)}</li>`).join("")}
      </ul>
    `;
  }

  htmlBody += `
      <hr style="margin-top: 24px; border: none; border-top: 1px solid #e5e5e5;" />
      <p style="color: #666; font-size: 12px;">Generated by AI Podcast Generator</p>
    </div>
  `;

  const maxRetries = 2;
  let lastError: Error | null = null;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      await transporter.sendMail({
        from: process.env.GMAIL_USER || "nickdavis0124@gmail.com",
        to,
        subject: `Your AI Podcast: ${topic}`,
        html: htmlBody,
        attachments: [
          {
            filename: `podcast-${timestamp}.mp3`,
            content: audioBuffer,
            contentType: "audio/mpeg",
          },
        ],
      });
      console.log(`Podcast email sent to ${to}`);
      return;
    } catch (error) {
      lastError = error as Error;
      console.error(`Email send attempt ${attempt + 1} failed:`, error);
      if (attempt < maxRetries - 1) {
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    }
  }

  throw lastError || new Error("Email sending failed after all retries");
}

export async function sendErrorEmail(
  to: string,
  topic: string,
  errorMessage: string
): Promise<void> {
  try {
    await transporter.sendMail({
      from: process.env.GMAIL_USER || "nickdavis0124@gmail.com",
      to,
      subject: `Podcast Generation Failed: ${topic}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #dc2626;">Podcast Generation Failed</h2>
          <p>We were unable to generate your podcast on the topic: <strong>${escapeHtml(topic)}</strong></p>
          <p>Error: ${escapeHtml(errorMessage)}</p>
          <p>Please try again later. If the issue persists, try with a different topic or shorter duration.</p>
          <hr style="margin-top: 24px; border: none; border-top: 1px solid #e5e5e5;" />
          <p style="color: #666; font-size: 12px;">Generated by AI Podcast Generator</p>
        </div>
      `,
    });
  } catch (emailError) {
    console.error("Failed to send error email:", emailError);
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
